name: Execute e2e android tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  mvn-run:
    uses: EtechCursos/workflow-calls/.github/wrokflows/java-e2e-testes.yaml@main
    secrets:
      git_token: ${{ secrets.TOKEN }}